name: Publish NuGet
on: workflow_dispatch

jobs:
  publish:
    name: Build, Pack & Publish
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.x
        include-prerelease: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Package
      run: dotnet pack -c Release -o . Source/WPF-Kanban.csproj

    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{secrets.NUGET_USER}}

    - name: Publish to nuget.org
      run: dotnet nuget push *.nupkg -k ${{steps.login.outputs.NUGET_API_KEY}}  -s https://api.nuget.org/v3/index.json