name: Publish NuGet
on: workflow_dispatch

jobs:
  publish:
    name: Build, Pack & Publish
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        include-prerelease: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Package
      run: dotnet pack -c Release -o . Source/WPF-Kanban.csproj
    - name: Publish to nuget.org

      run: dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json